controllers:
  resource: ../src/Controller/
  type: attribute

homepage:
  path: /
  controller: App\Controller\ArticleController::home

myaccount:
  path: /myaccount
  controller: App\Controller\ReporterController::index

articles:
  path: /articles
  controller: App\Controller\ArticleController::index

article_detail:
  path: /articles/{articleId}
  controller: App\Controller\ArticleController::show
  requirements:
    articleId: '\d+'   # Ensure articleId is a number

reporter_article_detail:
  path: /reporter/articles/{articleId}
  controller: App\Controller\ReporterArticleController::show
  requirements:
    articleId: '\d+'   # Ensure articleId is a number
    
add_article:
    path: /reporter/article/add
    controller: App\Controller\ReporterArticleController::add
    methods: [GET, POST]

article_edit:
    path: /reporter/article/{articleId}/edit
    controller: 'App\Controller\ReporterArticleController::edit'
    methods: ['GET', 'POST']

article_delete:
    path: reporter/articles/{articleId}/delete
    controller: 'App\Controller\ReporterArticleController::delete'
